substitutions:
  name: "template"
  friendly_name: "Template"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  project:
    name: esphome.project2-template
    version: "1.0"


bk72xx:
  board: generic-bk7231n-qfn32-tuya

 
dashboard_import:
  package_import_url: github://witchrobin/esphome/template-blk.yaml@main
  import_full_config: false # or true


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    
captive_portal:

improv_serial:
