substitutions:
  name: "tuya-switch"
  friendly_name: "Tuya Mini Switch"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
    
bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
web_server:
captive_portal:
mdns:
api:
  encryption:
    key: !secret api_key
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

binary_sensor:
  - platform: gpio
    id: binary_onoff_1
    pin:
      number: P26
      inverted: true
      mode: INPUT_PULLUP
    on_state:
      then:
        - switch.toggle: switch_1
  - platform: gpio
    id: binary_switch_all
    pin:
      number: P11
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P8

status_led:
  pin:
    number: P7
    inverted: true

button:
  - platform: factory_reset
    name: Reset to Factory Settings
  - platform: restart
    name: Restart
