substitutions:
  device_name: "tuya-mini"
  project_name: "Tuya.Mini Module"
  project_version: "1.1"
 
esphome:
  name: "${device_name}"
  friendly_name: "Tuya Mini Switch"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

api:

ota:

logger:

mdns:
  disabled: false

web_server:

wifi:
  ap: 

captive_portal:

dashboard_import:
  package_import_url: github://witchrobin/esphome/tuya-mini.yaml
